import type { Metadata } from "next";
import "./globals.css";
import { Header } from "../components/header";
import { Montserrat } from "next/font/google";

// 引入现代感字体 Montserrat
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 布局组件，设置全局背景、字体和几何装饰
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body
        className={`min-h-screen relative transition-colors ${montserrat.variable} font-sans`}
        style={{
          // 兼容性渐变背景
          background:
            "linear-gradient(135deg, #191923 0%, #333333 100%)",
        }}
      >
        {/* 绝对定位的科技感渐变光斑装饰 */}
        <div
          aria-hidden
          className="pointer-events-none select-none fixed -z-10 top-[-10%] left-[-10%] w-[60vw] h-[60vw] rounded-full opacity-40"
          style={{
            background:
              "radial-gradient(circle at 30% 30%, #9c27b0 0%, #00ffff 80%, transparent 100%)",
            filter: "blur(80px)",
          }}
        />
        <div
          aria-hidden
          className="pointer-events-none select-none fixed -z-10 bottom-[-15%] right-[-10%] w-[50vw] h-[50vw] rounded-full opacity-30"
          style={{
            background:
              "radial-gradient(circle at 70% 70%, #00ffff 0%, #9c27b0 60%, transparent 100%)",
            filter: "blur(100px)",
          }}
        />
        {/* 可添加更多几何渐变装饰 */}
        {/* 头部导航栏 */}
        <Header />
        {/* 主内容区，顶部留出导航栏空间，居中显示 */}
        <main className="pt-20 flex flex-col items-center justify-center">
          {children}
        </main>
      </body>
    </html>
  );
}

